version: "3"
services:
  mongodb:
    container_name: database_c
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    restart: always
    networks:
      - backend

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "4000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - backend

  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

volumes:
  mongo:

networks:
  frontend:
  backend:
