version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app

    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "80:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  db_data:
